# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/uart.xdc

# IP: ip/CDC_FIFO/CDC_FIFO.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CDC_FIFO || ORIG_REF_NAME==CDC_FIFO} -quiet] -quiet
